"""
rdft.ac.conserved_2
===================
Soft-mode-aware conservation projector for CDP/Manna-class DSEs.

This module is the v2 attempt at extending conserved.py from its current
"NESS rho_eff = const" scoping to a treatment that retains the
soft-mode IR contribution of the diffusive rho propagator.

The mathematical picture
------------------------
A polynomial DSE F(G, z) = G - z phi(G) generically has a Puiseux
branch of order 2 at its dominant singularity (Banderier-Drmota
"square-root"):
    F = 0,  dF/dG = 0  ==> k = 2  (codim 0).

A conserved field rho coupled via chi psi-tilde psi rho generates an
additional WARD IDENTITY at the branch point.  The conserved current
divergence d_mu J^mu = 0 implies that the chi vertex at zero external
momentum carries no anomalous dimension; the linear coupling
chi rho_NESS = const persists to all orders, AND the soft-mode
contribution from rho exchange generates a NON-LOCAL effective
psi-vertex whose coupling is TIED to chi (not independent).

This "tied-ness" is one constraint at the branch point.  It promotes
the Puiseux order:
    F = 0,  dF/dG = 0,  d^2F/dG^2 = 0  ==> k = 3  (codim 1).

The Banderier-Drmota dyadic ladder forbids non-dyadic k for purely
N-algebraic DSEs, but the conservation Ward identity introduces SIGNED
contributions (the back-coupling chi' rho-tilde psi-tilde psi) that
evade BD.  k = 3 is therefore accessible.

Implementation strategy
-----------------------
The soft-mode contribution is the loop integral
    Sigma_soft(p, omega) = chi^2 int d^d k d nu G_rho(k, nu) G_psi(p-k, omega-nu)
where G_rho(k, nu) = 1/(i nu + D' k^2) is the diffusive (massless)
propagator.  At zero external momentum and frequency, this integral
has an IR-divergent piece that EXACTLY cancels against the Ward
identity, leaving a finite contribution that EFFECTIVELY ADDS A NEW
QUARTIC VERTEX to the activity action:
    chi^2 / (D + D') * (psi-tilde psi)^2
This new vertex enters the activity DSE as a degree-3 term in G_psi
that is TIED to chi^2, not free.  The "tied-ness" of this term --
its coefficient is determined by chi, not by independent tuning --
is the codim-1 constraint that promotes k from 2 to 3.

This module implements that explicitly.  We:
1. Take the activity DP vertex set with coupling lambda.
2. Add the soft-mode-induced quartic with coupling chi^2 (CFAC's
   rank-2 bubble residue B_2 carries the loop normalisation).
3. Build the augmented activity DSE.
4. Test the Puiseux order.
5. If k = 3, extract gamma_3 at one loop from the rank-3 bridge.

Honest scope: this is a SIMPLIFIED model of the soft-mode
contribution.  It captures the codim counting that justifies C_3
slotting but does not derive the FRG flow rigorously (which would
require the full functional-RG machinery, not the algebraic stratification).
"""
from __future__ import annotations
import numpy as np
import sympy as sp
from typing import Optional

from .bridge import bridge_rank_k, upper_critical_dim_for_cusp
from .stratification import puiseux_order, on_stratum_C_k


def soft_mode_induced_vertex(chi: float, D_psi: float = 1.0,
                              D_rho: float = 1.0,
                              d_c: float = 4.0) -> dict:
    """Coefficient of the new effective psi-vertex generated by integrating
    out the soft mode of the conserved field rho.

    The activity-rho vertex chi psi-tilde psi rho, after rho is integrated
    out at one loop, generates an effective quartic
        S_eff = (chi^2 / 2) * int dx dx' (psi-tilde psi)(x)
                                G_rho(x - x') (psi-tilde psi)(x').

    At the upper critical dimension d_c = 4, the bubble integral
    int d^d k 1/[(D_psi + D_rho) k^2] reduces to the rank-2 bridge B_2
    times an IR-regularising factor.  The effective coupling is

        g_eff = chi^2 * B_2(d_c) / (D_psi + D_rho)

    Returns
    -------
    dict with the effective coupling and its breakdown.
    """
    B_2 = bridge_rank_k(2)  # = 2 / (1! (4 pi)^2) = 1/(8 pi^2)
    g_eff = chi**2 * B_2 / (D_psi + D_rho)
    return {
        'g_eff_quartic': g_eff,
        'B_2': B_2,
        'chi_squared': chi**2,
        'diffusion_sum': D_psi + D_rho,
        'derivation': (
            'Integrate out rho-fluctuations at one loop.  '
            'G_rho IR divergence is cancelled by Ward identity, leaving '
            'g_eff = chi^2 B_2 / (D_psi + D_rho).  '
            'This new quartic vertex is TIED to chi -- its strength is '
            'fixed by the coupling chi, not free to tune.'
        ),
    }


def cdp_dse_with_softmode(
        lambda_dp: float,
        chi: float,
        D_psi: float = 1.0,
        D_rho: float = 1.0,
        d_c: float = 4.0,
        z: Optional[sp.Symbol] = None,
        G: Optional[sp.Symbol] = None,
) -> dict:
    """Augmented activity DSE for CDP/Manna with soft-mode contribution.

    Vertices retained:
      - DP cubic: lambda_dp * psi-tilde psi^2  (gives -lambda_dp G^2 in phi)
      - Conservation linear: chi * rho_NESS * psi-tilde psi (mass shift)
      - Soft-mode induced quartic: g_eff * (psi-tilde psi)^2 (gives g_eff G^3 in phi)

    The KEY POINT is that the cubic and quartic vertices are NOT
    independently tunable: g_eff = chi^2 * B_2 / (D_psi + D_rho) is
    locked to chi.  This locking is the conservation Ward identity in
    DSE language; it removes one direction from the coupling space.

    DSE construction:
        phi(G) = 1 + (chi rho_NESS) G + (-lambda_dp) G^2 + g_eff G^3

    With rho_NESS = 1 (canonical normalisation) for simplicity.

    Returns
    -------
    dict containing:
      - phi_coefficients: list of phi(G) coefs, low to high
      - F_symbolic: F(G, z) = G - z phi(G) as sympy expression
      - puiseux_order: dominant Puiseux order
      - z_star: dominant branch point
      - on_C_3: whether the algebraic C_3 stratum is present
      - g_eff: the soft-mode effective coupling (TIED to chi)
      - notes: structural commentary
    """
    if z is None:
        z = sp.Symbol('z')
    if G is None:
        G = sp.Symbol('G')

    soft = soft_mode_induced_vertex(chi, D_psi, D_rho, d_c)
    g_eff = soft['g_eff_quartic']
    rho_NESS = 1.0  # canonical normalisation

    # phi(G) = 1 + a1 G + a2 G^2 + a3 G^3
    a1 = chi * rho_NESS
    a2 = -lambda_dp
    a3 = g_eff
    phi_coeffs = [1.0, a1, a2, a3]

    phi_sym = 1 + a1 * G + a2 * G**2 + a3 * G**3
    F = G - z * phi_sym

    # Puiseux analysis
    try:
        k_dom, z_star = puiseux_order(phi_coeffs)
    except Exception as e:
        k_dom, z_star = None, None
    is_C3 = on_stratum_C_k(phi_coeffs, 3) if len(phi_coeffs) >= 4 else False

    return {
        'phi_coefficients': phi_coeffs,
        'phi_symbolic': phi_sym,
        'F_symbolic': F,
        'puiseux_order': k_dom,
        'z_star': z_star,
        'on_C_3': is_C3,
        'g_eff': g_eff,
        'g_eff_breakdown': soft,
        'lambda_dp': lambda_dp,
        'chi': chi,
        'notes': (
            'Activity DSE augmented with soft-mode-induced quartic.  '
            'phi = 1 + (chi rho_NESS) G - lambda_dp G^2 + g_eff G^3, '
            'with g_eff = chi^2 B_2 / (D_psi + D_rho) TIED to chi.  '
            'The TIED-NESS of g_eff is the conservation Ward identity, '
            'removing one direction from the coupling space and '
            'promoting the Puiseux order at the branch point.'
        ),
    }


def find_C3_dominant_in_chi(
        lambda_dp: float = 1.0,
        chi_scan: list[float] = None,
        D_psi: float = 1.0,
        D_rho: float = 1.0,
) -> dict:
    """Scan the conservation coupling chi to find where C_3 is dominant.

    The Ward identity ties the quartic g_eff = chi^2 B_2 / (D_psi + D_rho)
    to chi.  As chi varies, the cubic and quartic couplings co-vary.  We
    expect a critical chi at which the dominant Puiseux order jumps from
    k=2 (DP-like) to k=3 (CDP-like).
    """
    if chi_scan is None:
        chi_scan = [0.0, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 20.0, 50.0, 100.0]
    rows = []
    transition_chi = None
    for chi in chi_scan:
        result = cdp_dse_with_softmode(lambda_dp, chi, D_psi, D_rho)
        rows.append({
            'chi': chi,
            'phi': result['phi_coefficients'],
            'g_eff': result['g_eff'],
            'k_dom': result['puiseux_order'],
            'z_star': result['z_star'],
            'on_C_3': result['on_C_3'],
        })
        if result['puiseux_order'] == 3 and transition_chi is None:
            transition_chi = chi
    return {
        'rows': rows,
        'transition_chi': transition_chi,
        'lambda_dp': lambda_dp,
    }


def gamma_3_from_softmode(d: float = 1.0, chi: float = 1.0,
                           lambda_dp: float = 1.0,
                           D_psi: float = 1.0, D_rho: float = 1.0) -> dict:
    """Compute the one-loop dressing gamma_3 at d, using the rank-3 bridge.

    Once we are on the C_3 stratum (g_eff TIED to chi by the Ward identity),
    the one-loop dressing comes from:
       gamma_3(d) = -n_eff * B_3 * eps^2
    where eps = d_c(3) - d = 3 - d and n_eff is the number of one-loop
    diagram channels at the C_3 multicritical fixed point.

    For the canonical CDP/Manna action, the relevant 1-loop channels are
    the THREE permutations of the symmetric quartic vertex contracted with
    itself (s, t, u channels), plus possible chi-cubic channels.  A
    minimal estimate: n_eff = 3 (just the symmetric quartic).

    Returns
    -------
    dict with gamma_3 estimate, B_3, eps, and the predicted tau.
    """
    B_3 = bridge_rank_k(3)
    d_c_3 = upper_critical_dim_for_cusp(3)  # = 3
    eps = d_c_3 - d
    n_eff_estimate = 3.0  # symmetric quartic, 3 channels (s, t, u)
    gamma_3 = -n_eff_estimate * B_3 * eps**2
    tau_skeleton = 1 + 1.0 / 3
    tau_predicted = tau_skeleton + gamma_3
    return {
        'd': d,
        'eps': eps,
        'B_3': B_3,
        'n_eff_estimate': n_eff_estimate,
        'gamma_3_estimate': gamma_3,
        'tau_skeleton': tau_skeleton,
        'tau_predicted': tau_predicted,
        'tau_observed_CDP_Manna': 1.30,
        'tau_observed_range': '[1.275, 1.338]',
        'agreement_within': abs(tau_predicted - 1.30),
        'notes': (
            'Order-of-magnitude estimate using n_eff = 3 (symmetric '
            'quartic channels).  More precise n_eff requires explicit '
            'enumeration of the 1-loop diagrams of the soft-mode-induced '
            'quartic, which depends on the specific microscopic '
            'realisation of the CDP/Manna class.'
        ),
    }
