"""Classic model specs — pure declarative data, zero model-specific code.

Each function returns a SimulationSpec dict (or object). These could equally
be JSON files loaded from disk or generated by an LLM. The engine is fully
generic — it runs any spec without knowing what model it represents.
"""

from sip_sim.spec import SimulationSpec

# ──────────────────────────────────────────────────────────────────────
# Conway's Game of Life
# ──────────────────────────────────────────────────────────────────────

GAME_OF_LIFE: dict = {
    "name": "Game of Life",
    "description": "Conway's Game of Life — emergent structure from 3 rules",
    "topology": {"kind": "grid", "width": 100, "height": 100, "wrap": True, "neighbourhood": "moore"},
    "agent_kinds": [
        {"name": "alive", "color": "#000000", "initial_fraction": 0.3},
    ],
    "rules": [
        {
            "name": "underpopulation",
            "condition": {"self_kind": "alive", "neighbour_kind_count": {"alive": {"lt": 2}}},
            "action": {"kind": "die"},
            "priority": 1,
        },
        {
            "name": "overpopulation",
            "condition": {"self_kind": "alive", "neighbour_kind_count": {"alive": {"gt": 3}}},
            "action": {"kind": "die"},
            "priority": 1,
        },
        {
            "name": "survival",
            "condition": {"self_kind": "alive", "neighbour_kind_count": {"alive": {"gte": 2, "lte": 3}}},
            "action": {"kind": "noop"},
            "priority": 1,
        },
        {
            "name": "birth",
            "condition": {"self_kind": "__empty__", "neighbour_kind_count": {"alive": {"eq": 3}}},
            "action": {"kind": "transform", "new_kind": "alive"},
            "priority": 0,
        },
    ],
    "observables": [
        {"name": "population", "kind": "count", "params": {"kind": "alive"}},
        {"name": "density", "kind": "density", "params": {"kind": "alive"}},
    ],
    "max_steps": 200,
    "snapshot_interval": 20,
    "seed": 42,
}

# ──────────────────────────────────────────────────────────────────────
# Schelling Segregation
# ──────────────────────────────────────────────────────────────────────

SCHELLING: dict = {
    "name": "Schelling Segregation",
    "description": "Mild individual preference (30%) produces extreme collective segregation",
    "topology": {"kind": "grid", "width": 50, "height": 50, "wrap": True, "neighbourhood": "moore"},
    "agent_kinds": [
        {"name": "red", "color": "#e74c3c", "initial_fraction": 0.45, "mobile": True},
        {"name": "blue", "color": "#3498db", "initial_fraction": 0.45, "mobile": True},
    ],
    "rules": [
        {
            "name": "red_unhappy",
            "condition": {"self_kind": "red", "neighbour_kind_fraction": {"red": {"lt": 0.3}}},
            "action": {"kind": "move", "params": {"scope": "global"}},
        },
        {
            "name": "blue_unhappy",
            "condition": {"self_kind": "blue", "neighbour_kind_fraction": {"blue": {"lt": 0.3}}},
            "action": {"kind": "move", "params": {"scope": "global"}},
        },
    ],
    "observables": [
        {"name": "red", "kind": "count", "params": {"kind": "red"}},
        {"name": "blue", "kind": "count", "params": {"kind": "blue"}},
        {"name": "segregation", "kind": "same_kind_fraction"},
    ],
    "max_steps": 100,
    "snapshot_interval": 10,
    "seed": 42,
}

# ──────────────────────────────────────────────────────────────────────
# Drossel-Schwabl Forest Fire
# ──────────────────────────────────────────────────────────────────────

FOREST_FIRE: dict = {
    "name": "Forest Fire",
    "description": "Self-organised criticality: growth vs lightning vs spread",
    "topology": {"kind": "grid", "width": 150, "height": 150, "wrap": False, "neighbourhood": "von_neumann"},
    "agent_kinds": [
        {"name": "tree", "color": "#2ecc71", "initial_fraction": 0.6},
        {"name": "burning", "color": "#e74c3c"},
    ],
    "rules": [
        {
            "name": "burnout",
            "condition": {"self_kind": "burning"},
            "action": {"kind": "die"},
            "priority": 3,
            "description": "Fire burns out in one step",
        },
        {
            "name": "fire_spread",
            "condition": {"self_kind": "tree", "neighbour_kind_count": {"burning": {"gte": 1}}},
            "action": {"kind": "transform", "new_kind": "burning"},
            "priority": 2,
        },
        {
            "name": "lightning",
            "condition": {"self_kind": "tree", "random_threshold": 0.00005},
            "action": {"kind": "transform", "new_kind": "burning"},
            "priority": 1,
        },
        {
            "name": "regrowth",
            "condition": {"self_kind": "__empty__", "random_threshold": 0.01},
            "action": {"kind": "transform", "new_kind": "tree"},
            "priority": 0,
        },
    ],
    "observables": [
        {"name": "trees", "kind": "count", "params": {"kind": "tree"}},
        {"name": "burning", "kind": "count", "params": {"kind": "burning"}},
        {"name": "tree_density", "kind": "density", "params": {"kind": "tree"}},
    ],
    "max_steps": 500,
    "snapshot_interval": 25,
    "seed": 42,
}

# ──────────────────────────────────────────────────────────────────────
# Predator-Prey (Lotka-Volterra on a grid)
# ──────────────────────────────────────────────────────────────────────

PREDATOR_PREY: dict = {
    "name": "Predator-Prey",
    "description": "Spatial Lotka-Volterra: prey reproduce, predators eat prey and reproduce, predators starve",
    "topology": {"kind": "grid", "width": 80, "height": 80, "wrap": True, "neighbourhood": "moore"},
    "agent_kinds": [
        {
            "name": "prey",
            "color": "#2ecc71",
            "initial_fraction": 0.3,
            "mobile": True,
            "state_schema": {"age": "float"},
            "initial_state": {"age": 0},
        },
        {
            "name": "predator",
            "color": "#e74c3c",
            "initial_fraction": 0.05,
            "mobile": True,
            "state_schema": {"hunger": "float"},
            "initial_state": {"hunger": 0},
        },
    ],
    "rules": [
        {
            "name": "predator_eats",
            "condition": {
                "self_kind": "predator",
                "neighbour_kind_count": {"prey": {"gte": 1}},
            },
            "action": {"kind": "modify_state", "state_update": {"hunger": "0"}},
            "priority": 3,
            "description": "Predator near prey resets hunger (prey dies via displacement)",
        },
        {
            "name": "predator_starve",
            "condition": {
                "self_kind": "predator",
                "self_state": {"hunger": {"gte": 10}},
            },
            "action": {"kind": "die"},
            "priority": 2,
            "description": "Predator dies after 10 steps without eating",
        },
        {
            "name": "predator_hunger_tick",
            "condition": {"self_kind": "predator"},
            "action": {"kind": "modify_state", "state_update": {"hunger": "+1"}},
            "priority": -1,
        },
        {
            "name": "prey_reproduce",
            "condition": {"self_kind": "prey", "random_threshold": 0.04},
            "action": {"kind": "spawn", "new_kind": "prey"},
            "priority": 1,
        },
        {
            "name": "predator_reproduce",
            "condition": {
                "self_kind": "predator",
                "self_state": {"hunger": {"lt": 3}},
                "random_threshold": 0.02,
            },
            "action": {"kind": "spawn", "new_kind": "predator"},
            "priority": 1,
        },
        {
            "name": "prey_move",
            "condition": {"self_kind": "prey"},
            "action": {"kind": "move"},
            "priority": 0,
            "rate": 0.5,
        },
        {
            "name": "predator_move",
            "condition": {"self_kind": "predator"},
            "action": {"kind": "move"},
            "priority": 0,
            "rate": 0.8,
        },
    ],
    "observables": [
        {"name": "prey", "kind": "count", "params": {"kind": "prey"}},
        {"name": "predators", "kind": "count", "params": {"kind": "predator"}},
    ],
    "max_steps": 500,
    "snapshot_interval": 25,
    "seed": 42,
}


# ──────────────────────────────────────────────────────────────────────
# Ant Clustering (Deneubourg et al. 1991 — abstracted)
# ──────────────────────────────────────────────────────────────────────
#
# In the Deneubourg model, ants pick up isolated food items and deposit
# them near clusters.  The NET effect on food is density-dependent
# mobility: isolated items move (high pickup prob), clustered items stay
# (low pickup prob).  We model this directly as food particles whose
# movement rate is a decreasing step-function of local food density.
#
# Expected: spatial entropy of food decreases; a few large clusters form.

ANT_CLUSTERING: dict = {
    "name": "Ant Clustering",
    "description": "Deneubourg-inspired: isolated food disperses, clustered food stays → clusters form",
    "topology": {"kind": "grid", "width": 80, "height": 80, "wrap": True, "neighbourhood": "moore"},
    "agent_kinds": [
        {"name": "food", "color": "#e67e22", "initial_fraction": 0.12},
    ],
    "rules": [
        {
            "name": "isolated_food_moves",
            "description": "Food with 0-1 food neighbours: high pickup by ants → teleports",
            "condition": {"self_kind": "food", "neighbour_kind_count": {"food": {"lte": 1}}},
            "action": {"kind": "move", "params": {"scope": "global"}},
            "rate": 0.9,
            "priority": 0,
        },
        {
            "name": "sparse_food_moves",
            "description": "Food with 2 food neighbours: moderate pickup",
            "condition": {"self_kind": "food", "neighbour_kind_count": {"food": {"eq": 2}}},
            "action": {"kind": "move", "params": {"scope": "global"}},
            "rate": 0.5,
            "priority": 0,
        },
        {
            "name": "loose_food_moves",
            "description": "Food with 3 food neighbours: low pickup",
            "condition": {"self_kind": "food", "neighbour_kind_count": {"food": {"eq": 3}}},
            "action": {"kind": "move", "params": {"scope": "global"}},
            "rate": 0.15,
            "priority": 0,
        },
        # food with ≥4 neighbours: no rule matches → stays (cluster is stable)
    ],
    "observables": [
        {"name": "food", "kind": "count", "params": {"kind": "food"}},
        {"name": "food_entropy", "kind": "spatial_entropy", "params": {"kind": "food", "block_size": 10}},
    ],
    "max_steps": 3000,
    "snapshot_interval": 300,
    "seed": 42,
}


# ──────────────────────────────────────────────────────────────────────
# Pheromone Trail Formation (Deneubourg/Goss 1990)
# ──────────────────────────────────────────────────────────────────────
#
# Ants deposit pheromone as they walk.  Pheromone evaporates and diffuses.
# Ants preferentially move toward higher pheromone (Deneubourg formula):
#   p(j) = (k + phi(j))^n / sum(...)
#
# Positive feedback: more ants → more pheromone → more ants.
# Expected: spontaneous trail/cluster formation, spatial entropy decreases.

ANT_PHEROMONE: dict = {
    "name": "Pheromone Trails",
    "description": "Ants deposit pheromone; follow gradients with momentum → spontaneous trail/highway formation",
    "topology": {"kind": "grid", "width": 100, "height": 100, "wrap": True, "neighbourhood": "moore"},
    "agent_kinds": [
        {
            "name": "ant",
            "color": "#e74c3c",
            "initial_fraction": 0.05,
            "mobile": True,
            "state_schema": {"dir_r": "float", "dir_c": "float"},
            "initial_state": {"dir_r": 0, "dir_c": 0},
        },
    ],
    "env_fields": [
        {"name": "pheromone", "initial_value": 0.0},
    ],
    "field_operations": [
        {"field": "pheromone", "kind": "decay", "rate": 0.08},
        {"field": "pheromone", "kind": "diffuse", "rate": 0.002},
    ],
    "rules": [
        {
            "name": "deposit_pheromone",
            "description": "Every ant deposits pheromone at its current cell",
            "condition": {"self_kind": "ant"},
            "action": {"kind": "modify_state", "state_update": {"pheromone": "+5.0"}},
            "priority": 1,
        },
        {
            "name": "follow_pheromone",
            "description": "Ants move toward higher pheromone with directional momentum",
            "condition": {"self_kind": "ant"},
            "action": {
                "kind": "move",
                "params": {
                    "bias_field": "pheromone",
                    "bias_strength": 3.0,
                    "bias_base": 0.1,
                    "momentum": 5.0,
                },
            },
            "priority": 0,
        },
    ],
    "observables": [
        {"name": "ants", "kind": "count", "params": {"kind": "ant"}},
        {"name": "ant_entropy", "kind": "spatial_entropy", "params": {"kind": "ant", "block_size": 10}},
        {"name": "pheromone_max", "kind": "env_max", "params": {"field": "pheromone"}},
        {"name": "pheromone_mean", "kind": "env_mean", "params": {"field": "pheromone"}},
        {"name": "alignment", "kind": "directional_alignment", "params": {"kind": "ant"}},
        {"name": "trail_linearity", "kind": "trail_linearity", "params": {"field": "pheromone", "threshold_frac": 0.3}},
    ],
    "max_steps": 2000,
    "snapshot_interval": 200,
    "seed": 42,
}


# ──────────────────────────────────────────────────────────────────────
# Pheromone Trail Formation — Non-Equilibrium (transient trails)
# ──────────────────────────────────────────────────────────────────────
#
# The edge-of-chaos regime: trails form spontaneously, persist for a
# while, then dissipate as ants explore new routes.  Unlike the
# equilibrium model above, the trail network never converges — it
# breathes, rewires, and reorganises continuously.
#
# Key differences from equilibrium regime:
#   - Lower momentum (1.5 vs 5.0): ants can leave established trails
#   - Higher evaporation (12% vs 8%): unused trails fade faster
#   - Moderate bias (1.8 vs 3.0): weaker gradient lock-in
#   - Higher bias_base (1.0 vs 0.1): random exploration competes
#   - More diffusion (1% vs 0.2%): trails smear slightly, reducing lock-in
#   - Faster heading adaptation (alpha=0.5 vs 0.3): less persistent heading
#
# The field_autocorrelation observable measures trail turnover:
#   - ~1.0 = frozen trails (equilibrium)
#   - ~0.0 = no structure (disorder)
#   - 0.3-0.7 = transient trails (edge of chaos) ← target

ANT_PHEROMONE_TRANSIENT: dict = {
    "name": "Pheromone Trails (Transient)",
    "description": "Non-equilibrium regime: trails form, shift, and dissolve — edge of chaos",
    "topology": {"kind": "grid", "width": 100, "height": 100, "wrap": True, "neighbourhood": "moore"},
    "agent_kinds": [
        {
            "name": "ant",
            "color": "#e74c3c",
            "initial_fraction": 0.025,
            "mobile": True,
            "state_schema": {"dir_r": "float", "dir_c": "float"},
            "initial_state": {"dir_r": 0, "dir_c": 0},
        },
    ],
    "env_fields": [
        {"name": "pheromone", "initial_value": 0.0},
    ],
    "field_operations": [
        {"field": "pheromone", "kind": "decay", "rate": 0.12},
        {"field": "pheromone", "kind": "diffuse", "rate": 0.003},
    ],
    "rules": [
        {
            "name": "deposit_pheromone",
            "description": "Every ant deposits pheromone at its current cell",
            "condition": {"self_kind": "ant"},
            "action": {"kind": "modify_state", "state_update": {"pheromone": "+6.0"}},
            "priority": 1,
        },
        {
            "name": "follow_pheromone",
            "description": "Ants follow pheromone with moderate momentum and some exploration",
            "condition": {"self_kind": "ant"},
            "action": {
                "kind": "move",
                "params": {
                    "bias_field": "pheromone",
                    "bias_strength": 2.5,
                    "bias_base": 0.3,
                    "momentum": 2.0,
                    "heading_alpha": 0.4,
                    "noise": 0.10,
                },
            },
            "priority": 0,
        },
    ],
    "observables": [
        {"name": "ants", "kind": "count", "params": {"kind": "ant"}},
        {"name": "ant_entropy", "kind": "spatial_entropy", "params": {"kind": "ant", "block_size": 10}},
        {"name": "pheromone_max", "kind": "env_max", "params": {"field": "pheromone"}},
        {"name": "pheromone_mean", "kind": "env_mean", "params": {"field": "pheromone"}},
        {"name": "alignment", "kind": "directional_alignment", "params": {"kind": "ant"}},
        {"name": "trail_linearity", "kind": "trail_linearity", "params": {"field": "pheromone", "threshold_frac": 0.3}},
        {"name": "trail_turnover", "kind": "field_autocorrelation", "params": {"field": "pheromone", "lag": 200}},
    ],
    "max_steps": 3000,
    "snapshot_interval": 300,
    "seed": 42,
}


# ──────────────────────────────────────────────────────────────────────
# Pheromone Trails — Simple 3-Parameter Model
# ──────────────────────────────────────────────────────────────────────
#
# A minimal model where ants have only three knobs:
#   p_follow    — probability of following pheromone gradient (vs random walk)
#   evaporation — pheromone decay rate per step
#   diffusion   — pheromone spreading rate per step
#
# Movement logic:
#   - With probability p_follow, pick neighbour weighted linearly by pheromone
#   - Otherwise, move randomly with directional momentum (persistence)
#   - Heading always updated via exponential moving average
#
# This eliminates bias_strength, bias_base, and noise as separate knobs.
# The interplay of just these three parameters should produce the full
# spectrum from disordered → transient trails → frozen highways.
#
# Momentum and heading_alpha are fixed structural constants (not swept),
# since they just control the "feel" of random walking, not the
# exploration/exploitation tradeoff.

ANT_PHEROMONE_SIMPLE: dict = {
    "name": "Pheromone Trails (Simple 3-Param)",
    "description": "Minimal model: p_follow vs random-with-momentum, plus evaporation and diffusion",
    "topology": {"kind": "grid", "width": 100, "height": 100, "wrap": True, "neighbourhood": "moore"},
    "agent_kinds": [
        {
            "name": "ant",
            "color": "#e74c3c",
            "initial_fraction": 0.04,
            "mobile": True,
            "state_schema": {"dir_r": "float", "dir_c": "float"},
            "initial_state": {"dir_r": 0, "dir_c": 0},
        },
    ],
    "env_fields": [
        {"name": "pheromone", "initial_value": 0.0},
    ],
    "field_operations": [
        {"field": "pheromone", "kind": "decay", "rate": 0.10},
        {"field": "pheromone", "kind": "diffuse", "rate": 0.005},
    ],
    "rules": [
        {
            "name": "deposit_pheromone",
            "description": "Every ant deposits pheromone at its current cell",
            "condition": {"self_kind": "ant"},
            "action": {"kind": "modify_state", "state_update": {"pheromone": "+5.0"}},
            "priority": 1,
        },
        {
            "name": "follow_or_wander",
            "description": "With p_follow probability follow pheromone, otherwise random walk with momentum",
            "condition": {"self_kind": "ant"},
            "action": {
                "kind": "move",
                "params": {
                    "bias_field": "pheromone",
                    "p_follow": 0.6,
                    "momentum": 3.0,
                    "heading_alpha": 0.3,
                },
            },
            "priority": 0,
        },
    ],
    "observables": [
        {"name": "ants", "kind": "count", "params": {"kind": "ant"}},
        {"name": "ant_entropy", "kind": "spatial_entropy", "params": {"kind": "ant", "block_size": 10}},
        {"name": "pheromone_max", "kind": "env_max", "params": {"field": "pheromone"}},
        {"name": "pheromone_mean", "kind": "env_mean", "params": {"field": "pheromone"}},
        {"name": "alignment", "kind": "directional_alignment", "params": {"kind": "ant"}},
        {"name": "trail_linearity", "kind": "trail_linearity", "params": {"field": "pheromone", "threshold_frac": 0.3}},
        {"name": "trail_turnover", "kind": "field_autocorrelation", "params": {"field": "pheromone", "lag": 200}},
    ],
    "max_steps": 2000,
    "snapshot_interval": 200,
    "seed": 42,
}


# ──────────────────────────────────────────────────────────────────────
# Registry — all models as plain dicts
# ──────────────────────────────────────────────────────────────────────

MODELS: dict[str, dict] = {
    "game_of_life": GAME_OF_LIFE,
    "schelling": SCHELLING,
    "forest_fire": FOREST_FIRE,
    "predator_prey": PREDATOR_PREY,
    "ant_clustering": ANT_CLUSTERING,
    "ant_pheromone": ANT_PHEROMONE,
    "ant_pheromone_transient": ANT_PHEROMONE_TRANSIENT,
    "ant_pheromone_simple": ANT_PHEROMONE_SIMPLE,
}


def load(name: str) -> SimulationSpec:
    """Load a named example spec. Validates the dict through Pydantic."""
    if name not in MODELS:
        raise KeyError(f"Unknown model '{name}'. Available: {list(MODELS.keys())}")
    return SimulationSpec(**MODELS[name])
